import Commands.*;
import Invoker.Invoker;
import MasterFunction.MasterFunction;
import Receiver.Receiver;

import java.util.ArrayList;
import java.util.Stack;

public class Main {
    public static void main(String[] args) {
        Stack<Command> history = new Stack<>();
        Receiver receiver = new Receiver();
        Invoker invoker = new Invoker();
        ArrayList<Command> c = new ArrayList<>();
        c.add(new ListCommand(receiver));
        c.add(new DeleteCommand(receiver,"a"));
        c.add(new DeleteCommand(receiver,"1"));
        c.add(new AddCommand(receiver, "first_name last_name email"));
        c.add(new AddCommand(receiver, "john doe simple@example.com"));
        c.add(new AddCommand(receiver, "hanna moon tetter.tots@potatoesarelife.com"));
        c.add(new AddCommand(receiver, "ah boon green-tea@teaforlife.com"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver, "3 aDam voX terra"));
        c.add(new UpdateCommand(receiver, "6 aDam voX terra"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver,"1 blue bell ice-cream@alaskafields.org"));
        c.add(new ListCommand(receiver));
        c.add(new DeleteCommand(receiver,"1"));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new DeleteCommand(receiver,"4"));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new DeleteCommand(receiver, "4"));
        c.add(new DeleteCommand(receiver, "3"));
        Command[] commands = c.toArray(new Command[c.size()]);
        invoker.setCommandsForExecution(commands);
        invoker.executeCommand(history);
        history.pop();
        c.clear();
        c.add(new UndoCommand(receiver,history));
        c.add(new ListCommand(receiver));
        commands = c.toArray(new Command[c.size()]);
        invoker.setCommandsForExecution(commands);
        invoker.executeCommand(history);
//        receiver.storeToFile();
//
//        String email = "aaa@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "aaa@bbb.ccc.";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "aaa@bb.b.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "aaa@bbb.c_cc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "aaa@bb_b.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "a.a.a@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "a__aa@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = ".aaa@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "aaa.@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "_aa-a.aaa_@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "a@b.c";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "a@b.cc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "@b.cc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "a@bb";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "a@bb.cccc.dd";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "dsadsadasa_";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "dsadsada.-sa_";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "d.-.-.sa-.--dsadasa_@gmail.com";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "d.-.-.sa-..dsadasa_@gmail.com";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
//        email = "d.-.-.s-.-.-.a-.-.d.-.-s-.-.a-.-.-d.-.-.asa_@d.-.-.s-.-.-.a-.-.d.-.-s-.-.a-.-.-d.-.-.asa.com";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
    }
}