import Commands.*;
import Invoker.Invoker;
import MasterFunction.MasterFunction;
import Receiver.Receiver;

import java.util.Stack;

public class Main {
    public static void main(String[] args) {
        Stack<Command> history = new Stack<>();
        Receiver receiver = new Receiver();
        Invoker invoker = new Invoker();
        Command[] commands = new Command[19];
        commands[0] = new ListCommand(receiver);
        commands[0] = new AddCommand(receiver, "first_name last_name email");
        commands[1] = new AddCommand(receiver, "john doe simple@example.com");
        commands[2] = new AddCommand(receiver, "hanna moon tetter.tots@potatoesarelife.com");
        commands[3] = new AddCommand(receiver, "ah boon green-tea@teaforlife.com");
        commands[4] = new ListCommand(receiver);
        commands[5] = new UpdateCommand(receiver, "3 aDam voX terra");
        commands[6] = new ListCommand(receiver);
        commands[7] = new UpdateCommand(receiver,"1 blue bell ice-cream@alaskafields.org");
        commands[8] = new ListCommand(receiver);
        commands[9] = new DeleteCommand(receiver,"1");
        commands[10] = new ListCommand(receiver);
        commands[11] = new UndoCommand(receiver, history);
        commands[12] = new ListCommand(receiver);
        commands[13] = new DeleteCommand(receiver,"4");
        commands[14] = new ListCommand(receiver);
        commands[15] = new UndoCommand(receiver, history);
        commands[16] = new ListCommand(receiver);
        commands[17] = new DeleteCommand(receiver, "4");
        commands[18] = new DeleteCommand(receiver, "3");
        invoker.setCommandsForExecution(commands);
        invoker.executeCommand(history);
        history.pop();
        commands = new Command[2];
        commands[0] = new UndoCommand(receiver,history);
        commands[1] = new ListCommand(receiver);
        invoker.setCommandsForExecution(commands);
        invoker.executeCommand(history);
        receiver.storeToFile();

        String email = "aaa@bbb.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "aaa@bbb.ccc.";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "aaa@bb.b.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "aaa@bbb.c_cc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "aaa@bb_b.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "a.a.a@bbb.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "a__aa@bbb.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = ".aaa@bbb.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "aaa.@bbb.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "_aa-a.aaa_@bbb.ccc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "a@b.c";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "a@b.cc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "@b.cc";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "a@bb";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "a@bb.cccc.dd";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "dsadsadasa_";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "dsadsada.-sa_";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "d.-.-.sa-.--dsadasa_@gmail.com";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "d.-.-.sa-..dsadasa_@gmail.com";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
        email = "d.-.-.s-.-.-.a-.-.d.-.-s-.-.a-.-.-d.-.-.asa_@d.-.-.s-.-.-.a-.-.d.-.-s-.-.a-.-.-d.-.-.asa.com";
        System.out.println(email + " - " + MasterFunction.checkIsValidEmail(email));
    }
}