import Commands.*;
import Invoker.Invoker;
import MasterFunction.MasterFunction;
import Receiver.Receiver;

import java.util.ArrayList;
import java.util.Stack;

public class Main {
    public static void main(String[] args) {
        Stack<Command> history = new Stack<>();
        Receiver receiver = new Receiver();
        Invoker invoker = new Invoker();
        ArrayList<Command> c = new ArrayList<>();
        c.add(new UndoCommand(null));
        c.add(new UndoCommand(null, history));
        c.add(new UndoCommand(receiver, history));
        c.add(new DeleteCommand(null, "1"));
        c.add(new DeleteCommand(receiver, "-1"));
        c.add(new DeleteCommand(receiver, "a"));
        c.add(new DeleteCommand(receiver, "1"));
        c.add(new ListCommand(receiver));
        c.add(new AddCommand(receiver, "first_name last_name email"));
        c.add(new AddCommand(receiver, "john doe simple@example.com"));
        c.add(new AddCommand(receiver, "hanna moon tetter.tots@potatoesarelife.com"));
        c.add(new AddCommand(receiver, "ah boon green-tea@teaforlife.com"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver, "3 aDam voX terra"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver, "3 black bell ice-cream@alaskafields.org"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver, "3 white"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver, "3 green ice"));
        c.add(new ListCommand(receiver));
        c.add(new UpdateCommand(receiver, "3 pink fire test"));
        c.add(new ListCommand(receiver));
        c.add(new DeleteCommand(receiver, "3"));
        c.add(new ListCommand(receiver));
        c.add(new DeleteCommand(receiver, "3"));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        c.add(new UndoCommand(receiver, history));
        c.add(new ListCommand(receiver));
        Command[] commands = c.toArray(new Command[c.size()]);
        invoker.setCommandsForExecution(commands);
        invoker.executeCommand(history);
//        receiver.storeToFile();

//        String email = "aaa@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "aaa@bbb.ccc.";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "aaa@bb.b.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "aaa@bbb.c_cc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "aaa@bb_b.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a.a.a@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a__aa@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = ".aaa@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "aaa.@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "_aa-a.aaa_@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "_aa--a.aaa_@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "_aa-a..aaa_@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "_aa-.a.aaa_@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "_aa-a.-aaa_@bbb.ccc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a@b.c";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a@b.cc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "@b.cc";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a@bb";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a@bb.cccc.dd";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a@bb.cccc.DD.dd";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "a@bb.cccc.DD";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "ABC_";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
//        email = "A.B-C_";
//        System.out.println(email + " - " + MasterFunction.checkIsValidEmailOrData3(email));
    }
}